fo = open('results.html', 'w')
fo.write("<html>\n")
fo.write("<head>\n")
fo.write("  <title>Not Written</title>\n")
fo.write("  <link rel='stylesheet' href='download.css'>\n")
fo.write("</head>\n")
fo.write("<body>\n")
fo.write("      <a rel='link' href='index.html'><img src='SUS (1).png' class='logo'></a>\n")
fo.write("<h1>Download the code from the source code page and run it to get the results.</h1>")
fo.write("</body>\n")
fo.write("</html>\n")
fo.close()